// <auto-generated />
using EquipAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EquipAPI.Data.Migrations
{
    [DbContext(typeof(EquipDbContext))]
    [Migration("20200810204210_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EquipsLibrary.Equips", b =>
                {
                    b.Property<string>("EquipsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EquipCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipsId");

                    b.ToTable("Equips");

                    b.HasData(
                        new
                        {
                            EquipsId = "e2c06985-9610-4962-8763-ee3d98e7c5c4",
                            EquipCount = "1",
                            EquipName = "Voidbow",
                            EquipType = "bow"
                        },
                        new
                        {
                            EquipsId = "4aef9cce-ba8e-4a65-9ed4-668e9ac768ef",
                            EquipCount = "15",
                            EquipName = "Leafbow",
                            EquipType = "bow"
                        },
                        new
                        {
                            EquipsId = "37bbe97c-a244-4d48-8cbb-373bb24380c9",
                            EquipCount = "10",
                            EquipName = "Doombow",
                            EquipType = "bow"
                        },
                        new
                        {
                            EquipsId = "36d90c21-35bf-44ef-940d-55c5ca2144be",
                            EquipCount = "25",
                            EquipName = "Coralbow",
                            EquipType = "bow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
